### ISSUE TITLE
Preliminary reading

### ISSUE THREAD

**Issue by Shinkson47** [Shinkson47/Data-CWK#2]
# A discussion of the project, coursework specification, and requirements.

Please refer to the specification for more detail.

**Comment by Shinkson47** [comment]
# General points of note from my first read.
- Due 28th Oct 2020, 12pm (Already created a Milestone for this)
- This is worth 60% of the module.
- Three parts, 100 marks.

- Expected output 
> - a zipped implementation (We can implement in anything, but we'll use java.)
> - a pdf outlining a solution, including a justifiable design and rationalisation.
Both parts are required for full marks.

**Comment by Shinkson47** [comment]
# Part 1 - The solution
- [ ] Outline assumptions made in solution, and how they may affect decisions made.
- [ ] Explain data structure used and how it stores the information.
> Use as much detail as possible, explain every aspect of the structure in its fullest.
> Use UML and Object relation diagrams to emphasise this.
- [ ] Link this data structure to the scenario, why's is the most appropriate solution?

- [ ] Provide coded library that can be used to generate the documented structure.
- [ ] Also provide a simple program that demonstrates this structure.

- [ ] Show how the data in the spec table would be stored within the data structure designed.
> Both in the demonstration programme,
> and the design documentation.

**Comment by Shinkson47** [comment]
# Part 2 - Justification (20 marks)
- [ ] Explain the reasons behind our choices.
> Consider the complexity in terms of time / space, and the ability for it to store the relevant data.
- [ ] Compare with alternate choices.

**Comment by Shinkson47** [comment]
# Part 3 - Operations (30 marks, 10 per operation)
- [ ] Demonstrate any three of the operations described in the task description
> We may also just make them up, as long as they're relevant enough.

- [ ] Explain how each of these operations would work using the data structure.
- [ ] Explain the time complexity of the operation.
> Ensure its clear which operation you're referring to.
